In [10]:
import numpy as np
a = np.arange(12).reshape((3,4))
print(a)
print(np.split(a,2,axis=1)) #np.split(ary,indices_or_sections,axis=1) 只能等量分 纵向
print(np.split(a,4,axis=1)) #np.split(ary,indices_or_sections,axis=1) 只能等量分 纵向
print(np.split(a,3,axis=0)) #np.split(ary,indices_or_sections,axis=1) 只能等量分 横向

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[array([[0],
       [4],
       [8]]), array([[1],
       [5],
       [9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [9]:
print(np.array_split(a,3,axis=1)) #np.array_split()  不等量的分割
print(np.array_split(a,3,axis=0)) #np.array_split()  不等量的分割

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [12]:
print(np.hsplit(a,2))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [14]:
print(np.vsplit(a,3))

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
