In [6]:
import numpy as np

a = np.array([2,23,4]) #创建数组
print(a)

[ 2 23  4]


In [7]:
a = np.array([2,23,4],dtype=np.int) #指定数据类型int
print(a.dtype)

int32


In [8]:
a = np.array([2,23,4],dtype=np.int32) #指定数据类型int32,位数越小占用的空间越小
print(a.dtype)

int32


In [9]:
a = np.array([2,23,4],dtype=np.float) #指定数据类型,也可以是float32
print(a.dtype)

float64


In [10]:
a = np.array([[2,23,4],
              [2,32,4]]) #创建特定数据，2行3列矩阵
print(a)

[[ 2 23  4]
 [ 2 32  4]]


In [11]:
a = np.zeros((3,4))#数据全为0，np.zeros((行,列))
print(a)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [13]:
a = np.ones((3,4),dtype = np.int16)#数据全为1，np.ones((行,列),指定类型)
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [14]:
a = np.empty((3,4))#每个值都接近于0，np.empty((行,列)) 
print(a)

[[  0.00000000e+000   4.94065646e-324   9.88131292e-324   1.48219694e-323]
 [  1.97626258e-323   2.47032823e-323   2.96439388e-323   3.45845952e-323]
 [  3.95252517e-323   4.44659081e-323   4.94065646e-323   5.43472210e-323]]


In [15]:
a = np.arange(10,20,2)#创建连续数组，np.arange(start,end,step) 10-19的数据
print(a)

[10 12 14 16 18]


In [4]:
import numpy as np
a = np.arange(12).reshape((3,4))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [8]:
a = np.linspace(1,10,5) #生成线段，np.linspace(start,end,count)开始端1，结束端10，且分割成5个数据生成线段
print(a)

[  1.     3.25   5.5    7.75  10.  ]


In [9]:
a = np.linspace(1,10,6).reshape((2,3))#更改shape 2行3列
print(a)

[[  1.    2.8   4.6]
 [  6.4   8.2  10. ]]
