In [7]:
import numpy as np
a = np.array([1,1,1])
b = np.array([2,2,2])
c = np.vstack((a,b)) #上下合并
print(c)
print(c.shape)
print(a.shape)

[[1 1 1]
 [2 2 2]]
(2, 3)
(3,)


In [6]:
d = np.hstack((a,b)) #左右合并
print(d)
print(d.shape)

[1 1 1 2 2 2]
(6,)


In [13]:
print(a.shape)
print(a)
print(a.T.shape)#没有变化
print(a[np.newaxis,:].shape)
print(a[np.newaxis,:])
print(a[:,np.newaxis].shape)
print(a[:,np.newaxis])

(3,)
[1 1 1]
(3,)
(1, 3)
[[1 1 1]]
(3, 1)
[[1]
 [1]
 [1]]


In [16]:
a = np.array([1,1,1])[np.newaxis,:]
b = np.array([2,2,2])[np.newaxis,:]
c = np.concatenate((a,b,a,a,b),axis=0) #合并多个数组concatenate axis=1横向axis=0纵向 
d = np.concatenate((a,b,a,a,b),axis=1)
print(a)
print(b)
print(c)
print(d)

[[1 1 1]]
[[2 2 2]]
[[1 1 1]
 [2 2 2]
 [1 1 1]
 [1 1 1]
 [2 2 2]]
[[1 1 1 2 2 2 1 1 1 1 1 1 2 2 2]]
