In [1]:
import numpy as np
a = np.array([10,20,30,40])
b = np.arange(4)
print(a,b)
c = a-b #对应元素相减
print(c)

[10 20 30 40] [0 1 2 3]
[10 19 28 37]


In [3]:
c = a+b #对应元素相加
print(c)

[10 21 32 43]


In [4]:
c = a*b #对应元素相乘
print(c)

[  0  20  60 120]


In [5]:
c = b**2 #b的二次方，注意**
print(c)

[0 1 4 9]


In [9]:
c = 10*np.sin(a) #求sin a
print(c)

[-0.54402111  0.91294525 -0.98803162  0.74511316]


In [10]:
print(b<3) #逻辑判断 <

[ True  True  True False]


In [22]:
a = np.array([[1,1],
               [0,1]])
b = np.arange(4).reshape((2,2))
#print(a)
#print(b)
c = a*b #逐个乘
print(c)
c_dot = np.dot(a,b)#矩阵乘
print(c_dot)
c_dot_2 = a.dot(b)
print(c_dot_2)

[[0 1]
 [0 3]]
[[2 4]
 [2 3]]
[[2 4]
 [2 3]]


In [28]:
a = np.random.random((2,4)) #随机数 在0-1之间
print(a)
#print(np.sum(a)) #求和
#print(np.max(a)) #寻最大值
#print(np.min(a)) #寻最小值
print(np.sum(a,axis=1))#axis=1 按行 axis=0按列
print(np.max(a,axis=0))#axis=1 按行 axis=0按列

[[ 0.47456448  0.58417191  0.82540274  0.1398232 ]
 [ 0.23750719  0.26469134  0.30482329  0.60326897]]
[ 2.02396233  1.4102908 ]
[ 0.47456448  0.58417191  0.82540274  0.60326897]
