In [1]:
import numpy as np
a = np.arange(3,15) #一维
print(a)
print(a[3])#索引从0开始 

[ 3  4  5  6  7  8  9 10 11 12 13 14]
6


In [5]:
a = np.arange(3,15).reshape((3,4)) #二维
print(a)
print(a[2])#索引为2的行
print(a[2,1])#索引[2,1]
print(a[2][1])#写法
print(a[:,1])#取列
print(a[1,1:3])#索引1行，1-3列


[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[11 12 13 14]
12
12
[ 4  8 12]
[8 9]


In [8]:
#迭代列:通过迭代转置矩阵的行来迭代列
for column in a.T:
   print(column)

[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


In [10]:
#迭代每一项
print(a.flatten()) #flatten()将多维矩阵展开成一行的数列
for item in a.flat: #flat是一个迭代器，本身是一个object属性
    print(item)

[ 3  4  5  6  7  8  9 10 11 12 13 14]
3
4
5
6
7
8
9
10
11
12
13
14
