In [19]:
import numpy as np
a = np.arange(2,14).reshape((3,4))
print(a)
print(np.argmin(a)) #最小值的索引
print(np.argmax(a)) #最大值的索引
print(np.mean(a)) #平均值 np.mean(a,axis=None,dtype=None,out=None,keepdims=False) axis=1按行axis=0按列
print(a.mean())
print(np.average(a))#平均值
print(np.median(a))#求中位数
print(np.cumsum(a))#累加 第二个数是第一个和第二个数的和，第三个数是第一、二、三个数的和
print(np.diff(a)) #与前一个数的差
print(np.nonzero(a))#非零元素的位置，第一个数组表示行数，第二个数组表示列数

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
0
11
7.5
7.5
7.5
7.5
[ 2  5  9 14 20 27 35 44 54 65 77 90]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))


In [28]:
a = np.arange(14,2,-1).reshape((3,4))
print(a)
print(np.transpose(a))#矩阵转置
print(np.sort(a))#按行排序
print(a.T)#矩阵转置
print((a.T).dot(a))

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]
[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[332 302 272 242]
 [302 275 248 221]
 [272 248 224 200]
 [242 221 200 179]]


In [29]:
print(np.clip(a,5,9)) #np.clip(array,a_min,a_max,out=None) 小于最小值的元素变成最小值，大于最大值的元素变成最大值

[[9 9 9 9]
 [9 9 8 7]
 [6 5 5 5]]


AttributeError: module 'numpy' has no attribute 'dim'