In [1]:
import numpy as np
a = np.arange(4)
b = a   #赋值方式带有关联性，一个改变全都改变
c = a
d = b
print(a)
print(b)
a[0] =11
print(c)
print(d)

[0 1 2 3]
[0 1 2 3]
[11  1  2  3]
[11  1  2  3]


In [4]:
a = np.arange(4) #deep copy赋值方式没有关联性
b = a.copy()
a[0] =  11
print(a)
print(b)

[11  1  2  3]
[0 1 2 3]
